# Generated by Django 5.1.6 on 2025-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_invite_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='statut',
            field=models.CharField(choices=[('COUPLE', 'couple'), ('MR', 'mr'), ('Miss', 'miss'), ('MADAME', 'madame')], default='COUPLE', max_length=11),
        ),
    ]
