# Generated by Django 5.1.6 on 2025-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invite_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='guest_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='capacite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
