# Generated by Django 5.1.6 on 2025-03-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_invite_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='photo',
            field=models.ImageField(blank=True, default='photos/wedding inv debo code QR 004 11.jpg', null=True, upload_to='photos_invites/'),
        ),
    ]
