# Generated by Django 5.1.6 on 2025-03-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_oath_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oath',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='oath',
            name='name',
        ),
        migrations.RemoveField(
            model_name='oath',
            name='number',
        ),
    ]
