# Generated by Django 5.1.6 on 2025-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_oath_first_name_remove_oath_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
