# Generated by Django 5.1.6 on 2025-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_invite_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='photo',
            field=models.ImageField(blank=True, default='photos/wedding inv debo code QR 004 11 1 1 1 1.jpg', null=True, upload_to='photos_invites/'),
        ),
    ]
